DROP DATABASE IF EXISTS TFC;
CREATE DATABASE IF NOT EXISTS TFC;
USE TFC;

CREATE TABLE IF NOT EXISTS usuarios (
    usuario VARCHAR(50) PRIMARY KEY,
    contrasena VARCHAR(100) NOT NULL
);

SELECT * FROM usuarios